---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-13.04
  - name: centos-6.4

suites:
  - name: default
    run_list: 
      - recipe[secure-server]
      - recipe[minitest-handler]
    attributes:
      'secure-server':
        ssh:
          password_authentication: false
          permit_root_login: false
        firewall:
          rules:
            - port: 22
              action: allow
            - port: 80
              action: allow
